# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pydantic data models and schemas for analytics-copilot workflow."""

from typing import Any, Optional
from pydantic import BaseModel, Field


class HypothesisTask(BaseModel):
    """A single hypothesis task to investigate in parallel."""

    id: str = Field(description="Unique identifier, e.g. H1, H2")
    title: str = Field(description="Short title of the hypothesis")
    rationale: str = Field(
        description="Reasoning why this hypothesis could explain the metric change"
    )
    base_filters: str = Field(
        description="Common cohort/denominator filter (e.g. status='Active' AND date >= '2026-01-01')"
    )
    target_metric: str = Field(
        description="Key metric to inspect (e.g. total_balance, payoff_rate, active_accounts)"
    )
    relevant_tables: list[str] = Field(
        default_factory=list,
        description="Warehouse tables relevant to this hypothesis (e.g. ['credit_cards', 'analytics_balances'])",
    )
    relevant_metrics: list[str] = Field(
        default_factory=list,
        description="Curated semantic metrics to compute (e.g. ['credit_card_payoff_rate', 'credit_card_spend'])",
    )
    relevant_dimensions: list[str] = Field(
        default_factory=list,
        description="Dimensions to slice by (e.g. ['customer_segment', 'card_type', 'month'])",
    )
    sql_intent: str = Field(
        description="Description of the SQL query needed to validate/refute this hypothesis"
    )


class HypothesisPlan(BaseModel):
    """Investigation plan generated by the planning agent."""

    business_question: str = Field(description="The parsed business question")
    common_base_cohort: str = Field(
        description="Shared denominator and cohort criteria across all hypotheses"
    )
    hypotheses: list[HypothesisTask] = Field(
        description="List of 1 to 7 hypotheses to investigate concurrently",
        min_length=1,
        max_length=7,
    )


class HypothesisResult(BaseModel):
    """Investigation result for a single hypothesis."""

    hypothesis_id: str = Field(description="ID of the hypothesis (e.g. H1)")
    title: str = Field(description="Title of the hypothesis")
    generated_sql: str = Field(description="SQL query executed against BigQuery/database")
    query_status: str = Field(description="SUCCESS or FAILED")
    scd2_applied: bool = Field(
        default=False,
        description="Whether Slowly Changing Dimension (SCD Type 2) filters (is_current/eff dates) were applied",
    )
    metrics_summary: dict[str, Any] = Field(
        default_factory=dict, description="Key extracted metrics and aggregates"
    )
    findings: str = Field(description="Analysis of whether the data supports or refutes the hypothesis")
    support_level: str = Field(
        description="CONFIRMED, REFUTED, or INCONCLUSIVE",
        default="INCONCLUSIVE",
    )


class RankedHypothesis(BaseModel):
    """Ranked contributing factor."""

    rank: int = Field(description="Rank order (1 being highest impact)")
    hypothesis_id: str = Field(description="ID of the hypothesis")
    title: str = Field(description="Title of the hypothesis")
    verdict: str = Field(description="CONFIRMED, REFUTED, or INCONCLUSIVE")
    estimated_impact: str = Field(description="Estimated contribution or impact magnitude")
    summary: str = Field(description="Brief summary of findings")


class AnalyticsSynthesis(BaseModel):
    """Final synthesis and executive narrative."""

    executive_summary: str = Field(
        description="High-level executive summary answering the stakeholder's question"
    )
    ranked_hypotheses: list[RankedHypothesis] = Field(
        description="Hypotheses evaluated and ranked by contribution"
    )
    sufficiency_verdict: str = Field(
        description="SUFFICIENT (evidence conclusively answers the question) or DEEP_DIVE_RECOMMENDED"
    )
    recommended_next_steps: list[str] = Field(
        description="Actionable recommendations or areas for deeper drill-down"
    )
    narrative_report: str = Field(
        description="Complete markdown report with data points and breakdown"
    )
